### ISSUE TITLE
cunumeric/legate eats the `-l` command line flag

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#415] opened 2022-10-05 22:29 UTC
The following program:
```
import cunumeric
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-l", type=int, default=None)
args, _ = parser.parse_known_args()
print(args.l)
```

run as `legate repro.py -l 5` will print `None`. However, if the `import cunumeric` is removed, then it will print 5. I don't see anywhere in the legate help messages etc why this might happen.

Pinging @bryevdv since you probably know what's up here.

**Comment by bryevdv** [comment] 2022-10-06 17:03
Note I have transferred this issue to `legate.core`

**Comment by manopapad** [comment] 2022-10-06 20:48
Noting for posterity, the root cause of this issue is that cpython 3.8 changed how argparse handles the interaction of single-dash options and `allow_abbrev`, see https://github.com/python/cpython/issues/85706.

**Closed** 2022-10-07 01:28 UTC
