### ISSUE TITLE
install.py doesn't respect --install-dir if it doesn't exist already

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#385] opened 2022-09-23 23:18 UTC
The validate_path function returns None when the directory doesn't exist, resulting in it getting overridden to some other value.

**Comment by manopapad** [comment] 2022-10-12 21:46
Looks like a duplicate of https://github.com/nv-legate/cunumeric/issues/600

**Closed by manopapad** 2022-10-12 21:46 UTC
